Loss Making leverage agent and common module
vesperfi/Forta-Agents pull request #2
Opened 2022-05-10 07:03 UTC by virendrapatidar

- Created Vesper Forta Module for common code to load pool, strategy, accountants etc from vesper API.

- Deployed [Loss Making leverage](https://explorer.forta.network/agent/0xfa3992ae723fedd5c3ef34d93aa110963ef73c0195afef32eb61a16ccb7263f3?_gl=1*2kwd6n*_ga*MTkxNTY4MzMwMS4xNjM5MjA3MDI2*_ga_3ERDDVRGQQ*MTY1MjE2NTQ4OS40My4xLjE2NTIxNjU5MTguMA..) strategy for avalanche chain

2022-05-10 13:00 UTC, jcvernaleo requested changes
One extra comment I think it needs but otherwise looking good.

2022-05-10 13:00 UTC, jcvernaleo commented on Vesper-Agents-Suite/vesper-forta-module/src/vesper.fetcher.ts
> +const IGNORE_ADDRESS = ["0xbA4cFE5741b357FA371b506e5db0774aBFeCf8Fc"];
Could you add a comment for what this address is (I know it is vvsp but looking back later it would help).

2022-05-10 13:52 UTC, virendrapatidar commented on Vesper-Agents-Suite/vesper-forta-module/src/vesper.fetcher.ts
> +const IGNORE_ADDRESS = ["0xbA4cFE5741b357FA371b506e5db0774aBFeCf8Fc"];
Added comments.

2022-05-10 19:13 UTC, jcvernaleo approved these changes
OK

2022-05-11 23:50 UTC, patidarmanoj10 approved these changes

2022-05-12 02:58 UTC, merged